version: '3.7'

services:

  workflows:
    build:
      context: ./src
      dockerfile: ./workflows/Tributech.Dataspace.WorkflowHost/Dockerfile
    networks:
      - internal-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5050
    ports:
      - "5050:5050"

  postgres:
    image: postgres:12
    restart: always
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    networks:
      - internal-net
    ports:
      - "5052:5432"
    volumes:
      - postgres:/data/postgres # named volume to avoid permission issue "data directory has wrong ownership"

  pgadmin:
    image: dpage/pgadmin4:4.27
    restart: always
    networks:
      - internal-net
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER:-postgres@tributech.io}
      PGADMIN_DEFAULT_PASSWORD: changeme
    volumes:
      - ./docker-compose-volumes/pgadmin_servers.json:/pgadmin4/servers.json

networks:
  internal-net:

volumes:
  postgres: